version: 2
updates:
- package-ecosystem: pip
  directory: "/api/requirements"
  schedule:
    interval: daily
  open-pull-requests-limit: 50
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: daily
  open-pull-requests-limit: 50
